// Generated from the user-provided ferramenta técnica de referência Printed Help DTC quick-reference.
// Applicability is vehicle-dependent; referência técnica explicitly states not every code is supported by every vehicle.
export const J1850_DTC_DESCRIPTIONS: Record<string, string> = {
  P0031: 'Front O2 Heater Low or Open',
  P0032: 'Front O2 Heater Shorted High',
  P0051: 'Rear O2 Heater Low or Open',
  P0052: 'Rear O2 Heater Shorted High',
  P0072: 'Ambient Temp Sensor Low',
  P0073: 'Ambient Temp Sensor High or Open',
  P0107: 'MAP Sensor Low or Open',
  P0108: 'MAP Sensor High',
  P0112: 'Intake Air Temperature Sensor Voltage Low',
  P0113: 'Intake Air Temperature Sensor Voltage High',
  P0117: 'Engine Temperature Sensor Voltage Low',
  P0118: 'Engine Temperature Sensor Voltage High',
  P0119: 'Engine Coolant Temperature Circuit Intermittent',
  P0120: 'Throttle Position Sensor #1 Range Error',
  P0122: 'Throttle Position Sensor #1 Low',
  P0123: 'Throttle Position Sensor #1 High',
  P0131: 'Front O2 Sensor Low',
  P0132: 'Front O2 Sensor High',
  P0134: 'Front O2 Sensor Open',
  P0137: 'Rear O2 Sensor Low',
  P0138: 'Rear O2 Sensor High',
  P0140: 'Rear O2 Sensor Open',
  P0151: 'Rear O2 Sensor Low',
  P0152: 'Rear O2 Sensor High',
  P0154: 'Rear O2 Sensor Open',
  P0197: 'Oil Temp Sensor Low',
  P0198: 'Oil Temp Sensor High',
  P0220: 'Throttle Position Sensor #2 Range Error',
  P0222: 'Throttle Position Sensor #2 Low/Open',
  P0223: 'Throttle Position Sensor #2 High',
  P0261: 'Front Injector Low or Open',
  P0262: 'Front Injector High or Shorted',
  P0263: 'Rear Injector Low or Open',
  P0264: 'Rear Injector High or Shorted',
  P0265: 'Rear Injector High or Shorted',
  P0325: 'Knock Sensor 1 Open Circuit',
  P0327: 'Knock Sensor 1 Circuit Low',
  P0328: 'Knock Sensor 1 Circuit High',
  P0330: 'Knock Sensor 2 Open Circuit',
  P0332: 'Knock Sensor 2 Circuit Low',
  P0333: 'Knock Sensor 2 Circuit High',
  P0371: 'EPS Too Few Pulses',
  P0372: 'EPS Too Many Pulses',
  P0373: 'Engine Position Sensor Intermittent',
  P0374: 'Engine Position Sensor Cannot Synchronize',
  P0375: 'Timing Reference High Resolution Signal B Malfunction',
  P0444: 'Purge Solenoid Low or Open',
  P0445: 'Purge Solenoid High or Shorted',
  P0462: 'Fuel Sender Shorted Low',
  P0463: 'Fuel Sender Shorted High',
  P0501: 'Vehicle Speed Sensor Shorted Low',
  P0502: 'Vehicle Speed Sensor Open or Shorted High',
  P0503: 'Vehicle Speed Sensor Failed High',
  P0505: 'Loss of Idle Speed Control',
  P0506: 'Idle Speed Too High',
  P0507: 'Idle Speed Too Low',
  P0512: 'Starter Request Stuck',
  P0522: 'Oil Pressure Sensor Low',
  P0523: 'Oil Pressure Sensor High or Open',
  P0562: 'System Voltage Low',
  P0563: 'System Voltage High',
  P0572: 'Brake Switch Input Error',
  P0577: 'Cruise Control Input Circuit High',
  P0603: 'EEPROM Memory Error',
  P0605: 'FLASH Memory Error',
  P0616: 'Starter Relay Coil Low',
  P0617: 'Starter Relay Coil High or Shorted',
  P0641: '5 Volt Vref #1 Out of Range',
  P0651: '5 Volt Vref #2 Out of Range',
  P0661: 'Intake Solenoid Low or Open',
  P0662: 'Intake Solenoid High or Shorted',
  P0691: 'Fan Relay Low or Open',
  P0692: 'Fan Relay High',
  P0693: 'Chassis Fan Control Circuit Low or Open',
  P0694: 'Chassis Fan Control Circuit Shorted High',
  P0704: 'Clutch Switch Stuck',
  P0851: 'Neutral Switch Stuck',
  P1001: 'System Relay Coil Low or Open',
  P1002: 'System Relay Coil High or Shorted',
  P1003: 'System Relay Contacts Failed Open',
  P1004: 'System Relay Contacts Failed Closed',
  P1005: 'Bank Angle Input Low',
  P1006: 'Bank Angle Input High',
  P1009: 'VTD Disabled Fuel, Bad Password',
  P1010: 'VTD Disabled Fuel, Missing Password',
  P1017: 'Engine Temp Indicates Overheating',
  P1019: 'Engine or Coolant Temp Indicates Overheating',
  P1100: 'Torque Control Fault',
  P1107: 'MAP Sensor Low but In Range',
  P1151: 'Bank Angle Sensor Low',
  P1152: 'Bank Angle Sensor High',
  P1270: 'Twistgrip Position Sensor #2 A/D Validation Error',
  P1351: 'Front Ignition Coil Open or Low',
  P1352: 'Front Ignition Coil High',
  P1353: 'Front Ignition Coil No Combustion',
  P1354: 'Rear Ignition Coil Open or Low',
  P1355: 'Rear Ignition Coil High',
  P1356: 'Rear Ignition Coil No Combustion',
  P1357: 'Front Ignition Coil Secondary Intermittent',
  P1358: 'Rear Ignition Coil Secondary Intermittent',
  P1472: 'Exhaust Actuator Position Feedback Low',
  P1473: 'Exhaust Actuator Position Feedback High',
  P1475: 'Exhaust Actuator Positioning Error',
  P1477: 'Exhaust Actuator Low/Open',
  P1478: 'Exhaust Actuator Shorted/High',
  P1481: 'Cooling Fan Relay Coil Low or Open',
  P1482: 'Cooling Fan Relay Coil Shorted High',
  P1501: 'Jiffy Stand Sensor Low',
  P1502: 'Jiffy Stand Sensor High/Open',
  P1505: 'Power Limit Violation',
  P1510: 'Throttle Actuator Control - Limited Performance Mode',
  P1511: 'Throttle Actuator Control - Power Management Mode',
  P1512: 'Throttle Actuator Control - Forced Idle Mode',
  P1514: 'Throttle Actuator Control - System Airflow Fault',
  P1600: 'Throttle Actuator Control - Processor Internal Fault',
  P1608: 'Loss of 12V Battery',
  P1632: 'ECM ODO adjusted to match Instrument ODO',
  P1651: 'Check Engine Light Output Low or Open',
  P1652: 'Check Engine Light Output High',
  P1653: 'Tachometer Output Low',
  P1654: 'Tachometer Output High',
  P1655: 'ACR Solenoid Low or Open',
  P1656: 'ACR Solenoid Shorted or High',
  P1691: 'Cooling Fan Low or Open',
  P1692: 'Cooling Fan Shorted or High',
  P1693: 'Cooling Fan B Low or Open',
  P1694: 'Cooling Fan B Shorted or High',
  P1772: 'Reverse Actuator Feedback Low',
  P1775: 'Reverse Actuator Feedback Error',
  P1777: 'Reverse Actuator Low',
  P1778: 'Reverse Actuator High',
  P1779: 'Reverse Actuator Open',
  P1781: 'Reverse Switch Input Error',
  P2100: 'Throttle Actuator Control - Motor Circuit Open',
  P2101: 'Throttle Actuator Control - Actuation Error',
  P2102: 'Throttle Actuator Control - Motor Circuit Low',
  P2103: 'Throttle Actuator Control - Motor Circuit High',
  P2105: 'Throttle Actuator Control - Forced Engine Shutdown',
  P2107: 'Throttle Actuator Control - Driver Internal Fault',
  P2119: 'Throttle Actuator Control - Actuator Return Fault',
  P2122: 'Twistgrip Position Sensor #1 Low/Open',
  P2123: 'Twistgrip Position Sensor #1 High',
  P2127: 'Twistgrip Position Sensor #2 Low/Open',
  P2128: 'Twistgrip Position Sensor #2 High',
  P2135: 'Throttle Position Sensor A/D Correlation Error',
  P2138: 'Throttle Position Sensor Correlation Error',
  P2176: 'Throttle Actuator Control - Closed Position Not Learned',
  P2184: 'Cooling Temp Sensor Voltage Low',
  P2185: 'Cooling Temp Sensor High or Open',
  P2300: 'Front Ignition Coil Driver Low or Open',
  P2301: 'Front Ignition Coil Driver High or Shorted',
  P2303: 'Rear Ignition Coil Driver Low or Open',
  P2304: 'Rear Ignition Coil Driver High or Shorted',
  P2600: 'Communication Line Open',
  P2602: 'Cooling Pump Low or Open',
  P2603: 'Cooling Pump Shorted or High',
  U0121: 'ABS Comm Lost',
  U0140: 'BCM Comm Lost',
  U0141: 'LHC Comm Lost',
  U0142: 'RHC Comm Lost',
  U0156: 'Instr #1 Comm Lost',
  U0157: 'Instr #2 Comm Lost',
  U0168: 'SCM Comm Lost',
  U0184: 'Radio Comm Lost',
  U0300: 'Module Software Incompatible',
  U0315: 'EHCU Error',
  U1064: 'TSSM Communications Lost',
  U1096: 'Instrument Panel Communications Lost',
  U1097: 'Speedometer Communications Lost',
  U1098: 'Tachometer Communications Lost',
  U1300: 'J1850 Shorted Low',
  U1301: 'J1850 Shorted High',
  U2064: 'EHCU Invalid Data Received, Plausibility',
  U2067: 'EHCU Invalid Data Received, Initialization Time',
  U2082: 'EHCU Invalid Data Received, Rolling Counter',
  U2083: 'EHCU Invalid Data Received, CRC',
  U2087: 'EHCU Invalid Data Received, Time Out',
};
