import React,{useEffect,useMemo,useRef,useState} from 'react';
import { Play,Pause,Trash2,Download,BrainCircuit,Save,GitCompare,FileText } from 'lucide-react';
import { DatalogSample,PacketLog,TelemetryData,ActiveDpidSnapshot } from '../types';
import { analyzeSession } from '../services/diagnosticAnalyzer';
import { analyzeFuelSession,compareFuelSessions,FuelTrend } from '../services/fuelSessionAnalyzer';
interface Props{telemetry:TelemetryData;logs?:PacketLog[]}
const n=(s:ActiveDpidSnapshot|undefined,k:string)=>{const v=s?.values?.[k];return typeof v==='number'&&Number.isFinite(v)?v:undefined};
const label=(t:FuelTrend)=>t==='LEAN_TENDENCY'?'TENDÊNCIA POBRE':t==='RICH_TENDENCY'?'TENDÊNCIA RICA':t==='ON_TARGET'?'PRÓXIMO DO ALVO':'DADOS INSUFICIENTES';
const fmt=(v:number|undefined,d=1)=>v===undefined?'—':v.toFixed(d);
export const DataloggerPanel:React.FC<Props>=({telemetry,logs=[]})=>{
 const [recording,setRecording]=useState(false),[samples,setSamples]=useState<DatalogSample[]>([]),[base,setBase]=useState<DatalogSample[]>([]); const start=useRef<number>();
 useEffect(()=>{if(!recording){start.current=undefined;return} if(!start.current)start.current=Date.now(); const id=setInterval(()=>{const now=Date.now(),d=telemetry.activeDpidData||{},d11=d['11'],d12=d['12'],d1a=d['1A'],d1d=d['1D']; const s:DatalogSample={timestamp:now,timeFormatted:new Date(now).toLocaleTimeString(),elapsedSec:(now-(start.current||now))/1000,rpm:telemetry.rpm,speedKmH:telemetry.speedKmH,engineTempC:telemetry.engineTempC,batteryVoltage:telemetry.batteryVoltage,throttlePosition:telemetry.throttlePosition,mapKpa:telemetry.manifoldPressureKpa,frontO2Mv:n(d1d,'O2 Front (mV)'),rearO2Mv:n(d1d,'O2 Rear (mV)'),frontO2RawMv:n(d1a,'O2 Raw Front (mV)'),rearO2RawMv:n(d1a,'O2 Raw Rear (mV)'),integratorFrontPct:n(d1d,'Integrator F (%)'),integratorRearPct:n(d1d,'Integrator R (%)'),longTermFrontPct:n(d1d,'Long Term F (%)'),longTermRearPct:n(d1d,'Long Term R (%)'),knockFrontDeg:n(d1a,'Knock Front (°)'),knockRearDeg:n(d1a,'Knock Rear (°)'),gear:String(telemetry.gear),sourceDpid11At:d11?.updatedAt,sourceDpid12At:d12?.updatedAt,sourceDpid1AAt:d1a?.updatedAt,sourceDpid1DAt:d1d?.updatedAt};setSamples(p=>[...p.slice(-19999),s]);},200);return()=>clearInterval(id)},[recording,telemetry]);
 const fuel=useMemo(()=>analyzeFuelSession(samples),[samples]),comparison=useMemo(()=>base.length?compareFuelSessions(base,samples):undefined,[base,samples]),report=useMemo(()=>analyzeSession(telemetry,samples,logs),[telemetry,samples,logs]);
 const csv=()=>{if(!samples.length)return;const h=['timestamp','elapsed_s','rpm','speed_kmh','gear','temp_c','battery_v','tps_pct','map_kpa','o2_front_mv','o2_rear_mv','integrator_front_pct','integrator_rear_pct','longterm_front_pct','longterm_rear_pct','o2raw_front_mv','o2raw_rear_mv','knock_front_deg','knock_rear_deg'];const rows=samples.map(s=>[new Date(s.timestamp).toISOString(),s.elapsedSec,s.rpm,s.speedKmH,s.gear??'',s.engineTempC,s.batteryVoltage,s.throttlePosition??'',s.mapKpa??'',s.frontO2Mv??'',s.rearO2Mv??'',s.integratorFrontPct??'',s.integratorRearPct??'',s.longTermFrontPct??'',s.longTermRearPct??'',s.frontO2RawMv??'',s.rearO2RawMv??'',s.knockFrontDeg??'',s.knockRearDeg??'']);download('\uFEFF'+[h,...rows].map(r=>r.join(';')).join('\r\n'),'conectaharley-datalog.csv','text/csv')};
 const exportReport=()=>{const lines=['ConeCtaHarley — Relatório da Sessão',new Date().toLocaleString(),'','IMPORTANTE: narrowband não é convertida em AFR.','','Resumo combustível:',`Amostras úteis: ${fuel.usableSamples}`,`Integrator médio: ${fmt(fuel.overallIntegrator,2)}%`,`Tendência: ${label(fuel.overall)}`,fuel.note,'','Faixas de operação:',...fuel.cells.slice(0,30).map(c=>`${c.gear} | ${c.rpmMin}-${c.rpmMax} rpm | TPS ${c.loadMin<0?'—':`${c.loadMin}-${c.loadMax}%`} | n=${c.samples} | Integrator ${c.avgIntegrator.toFixed(2)}% | ${label(c.trend)} | confiança ${c.confidence}`),'','Achados gerais:',...report.findings.flatMap(f=>[`${f.title}: ${f.status} — ${f.summary}`,...f.evidence.map(e=>`  • ${e}`)])];download(lines.join('\r\n'),'conectaharley-relatorio.txt','text/plain')};
 const download=(content:string,name:string,type:string)=>{const u=URL.createObjectURL(new Blob([content],{type:`${type};charset=utf-8`})),a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)};
 return <div className="space-y-5">
  <div className="bg-[#14151b] border border-neutral-800 rounded-2xl p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-black uppercase text-white flex items-center gap-2"><BrainCircuit className="w-5 h-5 text-violet-400"/>Datalog & Analisador</h2><p className="text-[11px] text-neutral-500">Medição real + análise determinística. Sem AFR artificial.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setRecording(v=>!v)} className="px-3 py-2 rounded-xl bg-emerald-700 text-xs font-bold flex gap-2 items-center">{recording?<Pause className="w-4 h-4"/>:<Play className="w-4 h-4"/>}{recording?'PAUSAR':'GRAVAR'}</button><button disabled={!samples.length} onClick={()=>setBase([...samples])} className="px-3 py-2 rounded-xl border border-neutral-700 text-xs font-bold flex gap-2 items-center disabled:opacity-40"><Save className="w-4 h-4"/>SALVAR COMO BASE</button><button disabled={!samples.length} onClick={csv} className="px-3 py-2 rounded-xl border border-neutral-700 text-xs font-bold flex gap-2 items-center disabled:opacity-40"><Download className="w-4 h-4"/>CSV</button><button disabled={!samples.length} onClick={exportReport} className="px-3 py-2 rounded-xl border border-neutral-700 text-xs font-bold flex gap-2 items-center disabled:opacity-40"><FileText className="w-4 h-4"/>RELATÓRIO</button><button onClick={()=>{setRecording(false);setSamples([])}} className="p-2 rounded-xl border border-neutral-700"><Trash2 className="w-4 h-4"/></button></div></div></div>
  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Amostras',samples.length],['Úteis O₂',fuel.usableSamples],['Integrator médio',fuel.overallIntegrator===undefined?'—':`${fuel.overallIntegrator.toFixed(2)}%`],['Tendência',label(fuel.overall)]].map(([a,b])=><div key={String(a)} className="bg-neutral-900 border border-neutral-800 rounded-xl p-3"><div className="text-[9px] uppercase text-neutral-500">{a}</div><div className="text-sm font-black text-white mt-1">{b}</div></div>)}</div>
  <div className="bg-neutral-900 border border-neutral-800 rounded-2xl p-5"><h3 className="text-xs font-black uppercase text-white">Mapa de tendência por faixa de operação</h3><p className="text-[10px] text-neutral-500 mt-1">Agrupamento em 500 rpm × 5% TPS × marcha. Células com poucas amostras permanecem inconclusivas.</p><div className="overflow-x-auto mt-4"><table className="w-full text-[11px]"><thead className="text-neutral-500"><tr><th className="text-left p-2">Marcha</th><th>RPM</th><th>TPS</th><th>Vel. média</th><th>Amostras</th><th>Integrator</th><th>Long Term</th><th>O₂ F/R</th><th>Tendência</th><th>Confiança</th></tr></thead><tbody>{fuel.cells.slice(0,24).map(c=><tr key={c.key} className="border-t border-neutral-800 text-center"><td className="p-2 text-left font-bold">{c.gear}</td><td>{c.rpmMin}-{c.rpmMax}</td><td>{c.loadMin<0?'—':`${c.loadMin}-${c.loadMax}%`}</td><td>{fmt(c.avgSpeed,1)} km/h</td><td>{c.samples}</td><td>{c.avgIntegrator.toFixed(2)}%</td><td>{fmt(c.avgLongTerm,2)}%</td><td>{fmt(c.avgFrontO2,0)} / {fmt(c.avgRearO2,0)} mV</td><td className="font-bold">{label(c.trend)}</td><td>{c.confidence}</td></tr>)}</tbody></table>{!fuel.cells.length&&<div className="text-center text-neutral-600 py-8">Grave uma sessão para gerar o mapa.</div>}</div></div>
  {base.length>0&&<div className="bg-neutral-900 border border-neutral-800 rounded-2xl p-5"><h3 className="text-xs font-black uppercase text-white flex gap-2"><GitCompare className="w-4 h-4"/>BASE × AJUSTE ATUAL</h3><p className="text-[10px] text-neutral-500 mt-1">Compara apenas células equivalentes de marcha/RPM/TPS com amostragem mínima.</p><div className="grid grid-cols-4 gap-2 mt-4 text-center">{[['Comparáveis',comparison?.comparableCells],['Melhoraram',comparison?.improved],['Semelhantes',comparison?.unchanged],['Pioraram',comparison?.worsened]].map(([a,b])=><div className="border border-neutral-800 rounded-xl p-3" key={String(a)}><div className="text-[9px] text-neutral-500">{a}</div><div className="font-black">{b??0}</div></div>)}</div></div>}
  <div className="bg-[#14151b] border border-neutral-800 rounded-2xl p-5"><h3 className="text-xs font-black uppercase text-white">Relatório diagnóstico geral</h3><div className="grid md:grid-cols-2 gap-3 mt-3">{report.findings.map(f=><div key={f.id} className="border border-neutral-800 rounded-xl p-3"><div className="flex justify-between gap-2"><b className="text-xs">{f.title}</b><span className="text-[9px] text-neutral-400">{f.status}</span></div><p className="text-[10px] text-neutral-500 mt-1">{f.summary}</p></div>)}</div></div>
 </div>;
};
